# Generated by Django 5.1.6 on 2025-03-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.list'),
        ),
    ]
